# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    AppBundle\Entity\User:
      algorithm: bcrypt

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    in_memory:
      memory: ~
    appbundle:
      id: AppBundle\Service\UserProvider

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: ~
      form_login:
        provider: appbundle
        csrf_token_generator: security.csrf.token_manager
        login_path: login
        check_path: login
        always_use_default_target_path: false
      logout:
        path: logout
        target: login
